//
// File generated by rootcint at Wed Apr 30 11:07:17 2014

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "fileseub1A.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

/********************************************************
* /media/LACIE_SHARE/Simulations/SPS/FINAL_H8/QMP32_exp/./fileseub1A.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablefileseub1A();

extern "C" void G__set_cpp_environmentfileseub1A() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/media/LACIE_SHARE/Simulations/SPS/FINAL_H8/QMP32_exp/./H8_style_study.c");
  G__cpp_reset_tagtablefileseub1A();
}
#include <new>
extern "C" int G__cpp_dllrevfileseub1A() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__fileseub1A__0_1262(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      H8_style_study();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncfileseub1A {
 public:
  G__Sizep2memfuncfileseub1A(): p(&G__Sizep2memfuncfileseub1A::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncfileseub1A::*p)();
};

size_t G__get_sizep2memfuncfileseub1A()
{
  G__Sizep2memfuncfileseub1A a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancefileseub1A() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablefileseub1A() {

   /* Setting up typedef entry */
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__fileseub1ALN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__fileseub1ALN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__fileseub1ALN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__fileseub1ALN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__fileseub1ALN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarfileseub1A() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncfileseub1A() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalfileseub1A() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
   G__memfunc_setup("H8_style_study", 1448, G__fileseub1A__0_1262, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcfileseub1A() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__fileseub1ALN_TVectorTlEfloatgR = { "TVectorT<float>" , 97 , -1 };
G__linked_taginfo G__fileseub1ALN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 97 , -1 };
G__linked_taginfo G__fileseub1ALN_TVectorTlEdoublegR = { "TVectorT<double>" , 97 , -1 };
G__linked_taginfo G__fileseub1ALN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 97 , -1 };
G__linked_taginfo G__fileseub1ALN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablefileseub1A() {
  G__fileseub1ALN_TVectorTlEfloatgR.tagnum = -1 ;
  G__fileseub1ALN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__fileseub1ALN_TVectorTlEdoublegR.tagnum = -1 ;
  G__fileseub1ALN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__fileseub1ALN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablefileseub1A() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__fileseub1ALN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileseub1ALN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__fileseub1ALN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileseub1ALN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__fileseub1ALN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
}
extern "C" void G__cpp_setupfileseub1A(void) {
  G__check_setup_version(30051515,"G__cpp_setupfileseub1A()");
  G__set_cpp_environmentfileseub1A();
  G__cpp_setup_tagtablefileseub1A();

  G__cpp_setup_inheritancefileseub1A();

  G__cpp_setup_typetablefileseub1A();

  G__cpp_setup_memvarfileseub1A();

  G__cpp_setup_memfuncfileseub1A();
  G__cpp_setup_globalfileseub1A();
  G__cpp_setup_funcfileseub1A();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncfileseub1A();
  return;
}
class G__cpp_setup_initfileseub1A {
  public:
    G__cpp_setup_initfileseub1A() { G__add_setup_func("fileseub1A",(G__incsetup)(&G__cpp_setupfileseub1A)); G__call_setup_funcs(); }
   ~G__cpp_setup_initfileseub1A() { G__remove_setup_func("fileseub1A"); }
};
G__cpp_setup_initfileseub1A G__cpp_setup_initializerfileseub1A;

