// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /media/LACIE_SHARE/Simulations/SPS/FINAL_H8/STF48_exp/./H8_style_study.c;

#endif
