/*
 * main_macro.C
 *
 *  Created on: Sep 21, 2016
 *      Author: fforcher
 */

//============================================================================
// Name        : bP_05.cpp
// Author      : Francesco Forcher
// Version     : 1.1
// Description : Modify Plot_v04 and use dispatcher&observers to handle begin/end job
//============================================================================
//#include "AnalysisFactory.h"
//#include "AnalysisInfo.h"
//#include "EventSource.h"
//#include "SourceFactory.h"
//#include "util/include/Dispatcher.h"
#include <iostream>
#include <vector>
#include <fstream>
#include <memory>
#include <TROOT.h>
#include <cstdlib>
#include "dbg_macro.h"

#include "mia_dech.h"


//Directory del progetto
TDirectory* PROJDIR = nullptr;

int main_macro(int argc, char* argv[]) {

	using namespace std;

	// store command line parameters

	int argc2 = 7;
	const char* argv2[] = { "./Debug/Ronch_braggPlot_v05", "input",
			"bragg_events.txt", "hist", "hh", "ranges", "energyRanges" };

	// TODO da leggere da un file eventualmente
	std::vector<const char*> elenco_cristalli { "STF45", "STF38" };

	cout << "Test main macro" << endl;

	// Corso root lunardon/garfagnini
	// carica la macro generica che legge il file di testo
	//gROOT->LoadMacro("ReadHistoFromTextFile.C");
	//gSystem->Load("ReadHistoFromTextFile_C.so"); // altra opzione per la precompilata

	/*
	 #if defined(__ROOTCLING__)
	 #pragma link C++ class MyOtherClass;
	 #endif
	 */
	//gROOT->LoadMacro("src/mia_dech.C");
	//gSystem->AddIncludePath(" -I./src/ ");
	//gROOT->ProcessLine(".L ./src/mia_dech.C+");
	//clog << "Fin qua" << endl;

	DBG(clog << "Current Dir: " << system("pwd") << endl
	; , ;)

	/* TODO Chiamare mia_dech su tutti i cristalli
	 * 1. Ottenere i file recoDataSimple_546_31-59.torsion.correction.histo.root
	 *
	 * 2. Scoprire dove sono le variabili
	 * 	//xtal length and curvature TODO Controllare!
	 Double_t z = 2e-3;
	 Double_t R;
	 * per gli altri cristalli (tabella in tesi di roberto?)
	 *
	 * 3. ???
	 * 4. Profit!
	 */

	//Shared because every crystal has to use it. Maybe not the best solution...
	std::shared_ptr<std::ofstream> outputdechanneling(
			new std::ofstream("./dechanneling_table.txt",
					std::ofstream::out | std::ofstream::trunc));

	*outputdechanneling
			<< "# File generated by the macro mia_dech() for the dechanneling lenghts."
			<< endl;
	*outputdechanneling
			<< "# Crystal | dechanneling L at +-5 microrad [m] | dechanneling L at +-10 microrad [m]"
			<< endl;
	PROJDIR = gDirectory;
	TDirectory* currentDir = gDirectory;
	for (const auto& ch : elenco_cristalli) {
		cout << endl << endl;
		//dech(ch, outputdechanneling);
		mions::mia_dech(ch, outputdechanneling);
		//currentDir->cd();
	}
	currentDir->cd();
	//mia_dech();

	//char t = 'a';
	//while (cin >> t)
	//	return 0;

	return 0;
}

